# Generated by Django 4.2 on 2023-04-20 15:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_tag_ingredient"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "different_app_name",
                    models.CharField(
                        choices=[
                            ("TICKET", "Ticket created"),
                            ("TICKET_HISTORY", "Ticket changed"),
                        ],
                        max_length=120,
                        verbose_name="app name",
                    ),
                ),
                (
                    "activate_or_not",
                    models.BooleanField(default=False, verbose_name="activate"),
                ),
            ],
            options={
                "verbose_name": "Configuration",
                "abstract": False,
            },
        ),
    ]
