# Generated by Django 4.2 on 2023-05-03 16:00
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0002_ingredient_unique_ingredient_upper_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ingredient",
            name="unique_ingredient_upper_name",
        ),
        migrations.RemoveConstraint(
            model_name="tag",
            name="unique_tag_upper_name",
        ),
    ]
