# Generated by Django 4.2 on 2023-04-21 08:29
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0003_applicationconfiguration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApplicationConfiguration",
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={"verbose_name": "Ingredient"},
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="recipe",
        ),
        migrations.AlterField(
            model_name="tag",
            name="recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipe.recipe",
                verbose_name="the related recipe",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="recipe",
            field=models.ManyToManyField(
                null=True, to="recipe.recipe", verbose_name="the related recipe"
            ),
        ),
    ]
