# Generated by Django 4.2 on 2023-04-21 12:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0005_remove_ingredient_recipe_remove_tag_recipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredient",
            field=models.ManyToManyField(to="recipe.ingredient"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tag",
            field=models.ManyToManyField(blank=True, to="recipe.tag"),
        ),
    ]
