# Generated by Django 4.2 on 2023-04-19 08:37
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="recipe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipe.recipe",
                verbose_name="the related recipe",
            ),
        ),
    ]
